# Immutable constants used by the Liljegren heat-balance equations.
STEFAN_BOLTZMANN <- 0.000000056696
CP_DRY_AIR <- 1003.5
MOLAR_MASS_AIR <- 28.97
MOLAR_MASS_WATER <- 18.015
UNIVERSAL_GAS_CONSTANT <- 8314.34
R_DRY_AIR <- UNIVERSAL_GAS_CONSTANT / MOLAR_MASS_AIR
PRANDTL_AIR <- CP_DRY_AIR / (CP_DRY_AIR + 1.25 * R_DRY_AIR)
WBGT_EVAPORATION_RATIO <- CP_DRY_AIR * MOLAR_MASS_AIR / MOLAR_MASS_WATER
